# -*- coding: utf-8 -*-
"""strings.xml 追加导出/分享/备份/课程管理资源。含 \n 的资源用转义序列写入。"""
import io

BS = chr(92)
ESC_N = BS + 'n'
p = 'app/src/main/res/values/strings.xml'
s = io.open(p, encoding='utf-8', newline='').read()
L = []
A = L.append
A('    <string name="import_close">关闭</string>')
A('')
A('    <!-- 导出/分享/备份。注意:分享文件名(Polaris课表.ics 等)、默认课表名"分享课表"为持久化数据,保持字面量。 -->')
A('    <string name="action_import_pdf">导入 PDF</string>')
A('    <string name="action_import_ai">AI 识别导入</string>')
A('    <string name="action_import_file">导入课表文件</string>')
A('    <string name="action_add_course">手动添加课程</string>')
A('    <string name="action_share_file">分享课表文件</string>')
A('    <string name="action_export">导出课表</string>')
A('    <string name="import_no_file_picker">未找到可选择课表文件的应用</string>')
A('    <string name="share_no_courses">还没有课程，先导入或添加课程后再分享</string>')
A('    <string name="share_dir_failed">无法创建课表分享目录</string>')
A('    <string name="share_file_subject">%1$s · Polaris课表</string>')
A('    <string name="share_file_text">使用 Polaris课程表 打开附件即可预览并导入。</string>')
A('    <string name="share_chooser_file">分享课表文件</string>')
A('    <string name="share_file_failed">生成课表分享文件失败：%1$s</string>')
A('    <string name="backup_dir_failed">无法创建备份目录</string>')
A('    <string name="backup_share_subject">Polaris课程表备份 · %1$s</string>')
A('    <string name="backup_share_text">使用 Polaris课程表 的「恢复备份」导入，即可完整还原课表与设置。</string>')
A('    <string name="backup_clip_label">Polaris备份文件</string>')
A('    <string name="backup_chooser_title">导出备份</string>')
A('    <string name="backup_picker_missing">未找到可选择文件的应用</string>')
A('    <string name="backup_read_unknown">无法读取备份文件</string>')
A('    <string name="backup_read_failed">备份文件读取失败：%1$s</string>')
A('    <string name="backup_version_unknown">未知版本</string>')
A('    <string name="backup_confirm_message">备份创建于 %1$s（来源 %2$s）' + ESC_N + '包含 %3$d 个课表 · 共 %4$d 门课程' + ESC_N + ESC_N + '恢复将覆盖本机当前所有课表和设置，且无法撤销。建议先导出当前数据作为备份。</string>')
A('    <string name="backup_confirm_action">恢复并覆盖本机数据</string>')
A('    <string name="backup_restore_failed">恢复失败：%1$s</string>')
A('    <string name="backup_restored_toast">已从备份恢复：%1$d 个课表 · %2$d 门课程</string>')
A('    <string name="export_busy">课表文件正在生成，请稍候</string>')
A('    <string name="export_dialog_title">导出课表</string>')
A('    <string name="export_dialog_message">选择周次导出单周课表，或把全学期课程合并到一张课表中导出。</string>')
A('    <string name="export_cd_week">导出周次</string>')
A('    <string name="export_cd_prev_week">上一周</string>')
A('    <string name="export_cd_next_week">下一周</string>')
A('    <string name="export_action_week_image">导出指定周图片</string>')
A('    <string name="export_action_week_pdf">导出指定周 PDF</string>')
A('    <string name="export_action_semester_pdf">导出整学期 PDF</string>')
A('    <string name="export_action_ics">导出 iCal 日历 (.ics)</string>')
A('    <string name="export_action_csv">导出 CSV (.csv)</string>')
A('    <string name="export_week_empty">本周没有课程，请切换到有课周后再导出</string>')
A('    <string name="export_generating_week_image">正在生成第 %1$d 周课表图片…</string>')
A('    <string name="export_generating_week_pdf">正在生成第 %1$d 周课表 PDF…</string>')
A('    <string name="export_semester_empty">当前课表没有课程，请先导入或添加课程</string>')
A('    <string name="export_generating_semester">正在生成整学期合并课表 PDF…</string>')
A('    <string name="export_failed_image">导出图片失败：</string>')
A('    <string name="export_failed_pdf">导出 PDF 失败：</string>')
A('    <string name="export_failed_semester">导出整学期 PDF 失败：</string>')
A('    <string name="export_start_failed">导出任务启动失败，请重试</string>')
A('    <string name="export_share_week_subject">%1$s · 第 %2$d 周</string>')
A('    <string name="export_share_week_text">Polaris课程表 · 第 %1$d 周</string>')
A('    <string name="export_clip_week_image">Polaris课表图片</string>')
A('    <string name="export_clip_week_pdf">Polaris课表 PDF</string>')
A('    <string name="export_clip_semester_pdf">Polaris整学期课表 PDF</string>')
A('    <string name="export_share_week_image_chooser">分享本周课表图片</string>')
A('    <string name="export_share_week_pdf_chooser">分享本周课表 PDF</string>')
A('    <string name="export_share_semester_chooser">分享整学期课表 PDF</string>')
A('    <string name="export_share_subject_semester">%1$s · 整学期合并课表</string>')
A('    <string name="export_share_text_semester">Polaris课程表 · 整学期合并课表</string>')
A('    <string name="export_share_panel_failed_image">图片已生成，但无法打开系统分享面板</string>')
A('    <string name="export_share_panel_failed_pdf">PDF 已生成，但无法打开系统分享面板</string>')
A('    <string name="export_share_panel_failed_semester">整学期 PDF 已生成，但无法打开系统分享面板</string>')
A('    <string name="export_ics_suffix">-日历.ics</string>')
A('    <string name="export_ics_label">iCal 日历</string>')
A('    <string name="export_ics_failed">导出 iCal 日历失败：%1$s</string>')
A('    <string name="export_csv_failed">导出 CSV 失败：%1$s</string>')
A('    <string name="export_dir_failed">无法创建导出目录</string>')
A('    <string name="calendar_share_subject">Polaris课程表 · %1$s · %2$s</string>')
A('    <string name="calendar_clip_label">Polaris%1$s文件</string>')
A('    <string name="calendar_share_chooser">分享%1$s文件</string>')
A('    <string name="calendar_share_panel_failed">%1$s已生成，但无法打开系统分享面板</string>')
A('    <string name="shared_file_invalid">文件中的课表数据无效</string>')
A('    <string name="shared_file_read_failed">无法读取文件内容</string>')
A('    <string name="shared_file_import_failed">课表文件导入失败：%1$s</string>')
A('    <string name="shared_link_title">链接导入</string>')
A('    <string name="shared_link_message">粘贴 Polaris 课程表分享链接，确认后可直接导入。</string>')
A('    <string name="shared_link_empty">请先粘贴分享链接</string>')
A('    <string name="shared_link_invalid">这不是有效的 Polaris 课表分享链接</string>')
A('    <string name="shared_link_no_courses">分享链接里没有可导入的课程</string>')
A('    <string name="shared_link_invalid_toast">课表分享链接无效：%1$s</string>')
A('    <string name="shared_import_title">导入分享课表？</string>')
A('    <string name="shared_import_message">分享链接包含 %1$d 门课程，继续导入会覆盖当前课表。</string>')
A('')
A('    <!-- 课程管理(查看所有课程/批量操作)。 -->')
A('    <string name="manage_title_select">选择课程</string>')
A('    <string name="manage_title_all">全部课程</string>')
A('    <string name="manage_stats_course">课程 %1$d 门</string>')
A('    <string name="manage_stats_experiment"> · 实验 %1$d</string>')
A('    <string name="manage_stats_practice"> · 实践 %1$d</string>')
A('    <string name="manage_stats_online"> · 网络 %1$d</string>')
A('    <string name="manage_stats_weekly">' + ESC_N + '每周课时 %1$d 节 · 学期共 %2$d 节</string>')
A('    <string name="manage_stats_credit"> · 学分 %1$s</string>')
A('    <string name="manage_stats_teacher">' + ESC_N + '教师 %1$d 位</string>')
A('    <string name="manage_stats_top_teacher"> · %1$s %2$d 门</string>')
A('    <string name="manage_stats_cd">课程统计，%1$s</string>')
A('    <string name="manage_search_hint">搜索课程 / 教师 / 地点</string>')
A('    <string name="manage_search_cd">搜索课程</string>')
A('    <string name="manage_select_done">完成</string>')
A('    <string name="manage_select_multi">多选</string>')
A('    <string name="manage_select_done_cd">完成多选</string>')
A('    <string name="manage_select_multi_cd">进入多选</string>')
A('    <string name="manage_action_color">改颜色</string>')
A('    <string name="manage_action_teacher">改教师</string>')
A('    <string name="manage_action_delete">删除</string>')
A('    <string name="manage_selected_count">已选 %1$d 门</string>')
A('    <string name="manage_old_data_unsupported">该课程数据较旧，暂不支持批量操作</string>')
A('    <string name="manage_error_no_selection">请先选择课程</string>')
A('    <string name="manage_batch_color_title">批量修改颜色</string>')
A('    <string name="manage_batch_color_message">为选中的 %1$d 门课程设置统一颜色。</string>')
A('    <string name="manage_swatch_cd">选择颜色</string>')
A('    <string name="manage_batch_teacher_title">批量修改教师</string>')
A('    <string name="manage_batch_teacher_message">为选中的 %1$d 门课程设置统一教师（覆盖原有教师信息）。</string>')
A('    <string name="manage_teacher_hint">教师姓名</string>')
A('    <string name="manage_error_teacher_empty">请输入教师姓名</string>')
A('    <string name="manage_batch_delete_title">批量删除课程</string>')
A('    <string name="manage_batch_delete_message">删除选中的 %1$d 门课程（包括全部上课安排）？该操作无法撤销。</string>')
A('    <string name="manage_batch_delete_action">删除选中课程</string>')
A('    <string name="manage_error_nothing_updated">没有可更新的课程</string>')
A('    <string name="manage_updated_color">已更新 %1$d 门课程的颜色</string>')
A('    <string name="manage_updated_teacher">已更新 %1$d 门课程的教师</string>')
A('    <string name="manage_error_nothing_deleted">没有可删除的课程</string>')
A('    <string name="manage_deleted">已删除 %1$d 门课程</string>')
A('</resources>')
block = '\n'.join(L)
old_tail = '    <string name="import_close">关闭</string>\n</resources>'
assert s.count(old_tail) == 1
s = s.replace(old_tail, block)
io.open(p, 'w', encoding='utf-8', newline='').write(s)
print('OK: strings.xml +93')
